version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inlog-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./back-end/Inlog.Desafio.Backend
      dockerfile: Inlog.Desafio.Backend.WebApi/Dockerfile
    image: inlog-desafio-backend:webapi
    container_name: inlog-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=db;Database=InlogDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080
        REACT_APP_USE_MIRAGE: "false"
    image: inlog-desafio-frontend:app
    container_name: vehicle-management-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  sqlserver_data:
